import { EditorialPage } from "@/components/EditorialPage";

export default function PrivacyPage() { return <EditorialPage eyebrow="PRIVACY POLICY · EFFECTIVE 15 AUGUST 2026" title={<>Private motion.<br/><em>Public provenance.</em></>} intro="The recording is analysed locally in your browser. Minting creates public blockchain records, so the privacy boundary changes when you connect and transact.">
  <section><h2>Information processed locally</h2><p>Pointer, touch, or stylus coordinates, timing, pressure where available, velocity, acceleration, curvature, pauses, taps, turns, and coverage are processed on your device to derive the artwork and seed. The app does not need a camera, microphone, name, email address, or biometric identity for generation.</p></section>
  <section><h2>Wallet and blockchain data</h2><p>When you connect a wallet, the interface reads the public address, selected network, token ownership, transaction status, and contract data required to display and mint NFTs. Confirmed wallet addresses, transfers, token IDs, and transaction data are permanently public on Base.</p></section>
  <section><h2>Device storage</h2><p>Prepared mint and recovery information may be stored in your browser so an interrupted mint can resume. You can remove it by clearing site data, but doing so may remove local recovery information.</p></section>
  <section><h2>Permanent media and metadata</h2><p>When you prepare a mint, the still artwork, living artwork, renderer version, seed, and metadata may be uploaded to permanent or content-addressed storage. Information included in minted metadata should be treated as public and difficult or impossible to delete.</p></section>
  <section><h2>External services</h2><p>WalletConnect, wallet applications, Base infrastructure, IPFS services, OpenSea, and linked House of Joshi sites may process technical or account information under their own privacy policies.</p></section>
  <section><h2>Your choices</h2><p>You may explore without connecting a wallet, stop a recording, decline a transaction, clear browser data, or use a different wallet. Blockchain records cannot be erased by this website.</p></section>
  <section><h2>Contact</h2><p>Privacy questions can be submitted through <a href="https://thehouseofjoshi.com/contact" target="_blank" rel="noreferrer">The House of Joshi contact page ↗</a>.</p></section>
 </EditorialPage>; }
