"use client";

import { useEffect, useState } from "react";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { useReadContract, useSwitchChain, useWaitForTransactionReceipt, useWriteContract } from "wagmi";
import { base } from "wagmi/chains";
import { decodeEventLog, isHex } from "viem";
import { openSeaItemUrl, oneMinuteContractAbi, oneMinuteContractAddress } from "@/lib/contract";
import type { ArtworkMetadata } from "@/lib/export";
import { loadPreparedMint, savePreparedMint, type PreparedMint } from "@/lib/mint-recovery";
import { track } from "@/lib/telemetry";

export default function BaseMintButtonInner({ seedHash, metadata, canvas }: { seedHash: string; metadata?: ArtworkMetadata; canvas?: HTMLCanvasElement | null }) {
  const [prepared, setPrepared] = useState<PreparedMint | null>(() => typeof window === "undefined" ? null : loadPreparedMint(seedHash)); const [status, setStatus] = useState(""); const [preparing, setPreparing] = useState(false); const [transactionHash, setTransactionHash] = useState<`0x${string}` | undefined>(); const { switchChainAsync } = useSwitchChain(); const { writeContractAsync, isPending } = useWriteContract(); const receipt = useWaitForTransactionReceipt({ hash: transactionHash });
  const prepare=async()=>{if(!canvas||!metadata)return;track("mint_preparation_started");setPreparing(true);setStatus("Pinning still, living artwork, and metadata to public IPFS…");try{const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/png"));if(!blob)throw new Error("The artwork canvas could not be captured.");const form=new FormData();form.set("artwork",new File([blob],"artwork.png",{type:"image/png"}));form.set("metadata",JSON.stringify(metadata));const response=await fetch("/api/mint/prepare",{method:"POST",body:form});const payload=await response.json() as PreparedMint&{error?:string};if(!response.ok)throw new Error(payload.error||"Permanent storage failed.");const next={...payload,seedHash,preparedAt:new Date().toISOString(),state:"prepared" as const};savePreparedMint(next);setPrepared(next);setStatus("Permanent mint files are ready. They will be reused if the wallet flow is interrupted.");}catch(error){track("mint_preparation_failed");setStatus(error instanceof Error?error.message:"Permanent storage failed.");}finally{setPreparing(false);}};
  const metadataURI=prepared?.metadataURI||"";
  const enabled = Boolean(oneMinuteContractAddress && /^ipfs:\/\/.+/.test(metadataURI) && isHex(seedHash, { strict: true }) && seedHash.length === 66);
  const price = useReadContract({ address: oneMinuteContractAddress, abi: oneMinuteContractAbi, functionName: "MINT_PRICE", query: { enabled: Boolean(oneMinuteContractAddress) } });
  const isOpen = useReadContract({ address: oneMinuteContractAddress, abi: oneMinuteContractAbi, functionName: "publicMintOpen", query: { enabled: Boolean(oneMinuteContractAddress) } });
  const mint = async () => { if (!enabled || !oneMinuteContractAddress || typeof price.data !== "bigint" || !prepared) return; setStatus("Checking Base network…"); try { await switchChainAsync({ chainId: base.id }); setStatus("Confirm in your wallet…"); const hash = await writeContractAsync({ address: oneMinuteContractAddress, abi: oneMinuteContractAbi, functionName: "mintOneMinute", args: [seedHash as `0x${string}`, prepared.houseIndex, prepared.traitsHash, prepared.rendererVersion, metadataURI], value: price.data, chainId: base.id }); setTransactionHash(hash); track("mint_submitted"); savePreparedMint({...prepared,transactionHash:hash,state:"submitted"}); setStatus("Transaction pending on Base…"); } catch(error) { track("mint_failed"); const lastError=error instanceof Error?error.message:"Wallet transaction was not completed."; savePreparedMint({...prepared,state:"failed",lastError}); setStatus("Mint was not completed. Your permanent files are saved; reconnect and retry safely."); } };
  const tokenId = receipt.data?.logs.flatMap(log=>{try{const event=decodeEventLog({abi:oneMinuteContractAbi,data:log.data,topics:log.topics});return event.eventName==="OneMinuteMinted"&&"tokenId" in event.args?[event.args.tokenId as bigint]:[]}catch{return[]}})[0];
  useEffect(()=>{if(!receipt.isSuccess||!transactionHash||!prepared||prepared.state==="confirmed")return;savePreparedMint({...prepared,transactionHash,tokenId:tokenId?.toString(),state:"confirmed"});track("mint_confirmed",{tokenId:Number(tokenId||0)})},[receipt.isSuccess,transactionHash,prepared,tokenId]);
  if (!oneMinuteContractAddress) return <p className="mint-note">Base mint is ready in the app, but the verified contract address has not been configured yet.</p>;
  return <ConnectButton.Custom>{({ account, openConnectModal, mounted }) => {
    if (!mounted || !account) return <button className="primary-button" onClick={openConnectModal}>Connect to mint on Base <span>◆</span></button>;
    const minted = receipt.isSuccess && transactionHash;
    return <div className="base-mint"><p className="mint-steps">01 WALLET CONNECTED <b>→</b> 02 PERMANENT STORAGE <b>→</b> 03 CONFIRM <b>→</b> 04 MINTED</p>{prepared?<div className="storage-ready"><b>IPFS READY</b><span>{prepared.metadataURI}</span></div>:<button className="secondary-button" onClick={prepare} disabled={preparing||!canvas||!metadata}>{preparing?"Preparing permanent files…":"Prepare permanent mint files"}</button>}<small>The still PNG, living HTML artwork, and versioned metadata are pinned before the wallet transaction. A recovery record stays on this device until mint completion.</small>{isOpen.data === false && <p className="action-error">Public mint is not open yet.</p>}<button className="primary-button" onClick={mint} disabled={!enabled || isPending || receipt.isLoading || isOpen.data === false}>{isPending ? "Confirm in wallet…" : receipt.isLoading ? "Mint pending on Base…" : `Mint on Base${typeof price.data === "bigint" ? " · " + Number(price.data) / 1e18 + " ETH" : ""}`}<span>↗</span></button>{status && <p className="mint-note">{status}</p>}{minted && <p className="mint-note">Minted. <a href={`https://basescan.org/tx/${transactionHash}`} target="_blank" rel="noreferrer">View on BaseScan ↗</a>{tokenId&&openSeaItemUrl(tokenId)&&<> · <a href={openSeaItemUrl(tokenId)} target="_blank" rel="noreferrer">OpenSea indexing ↗</a></>}</p>}</div>;
  }}</ConnectButton.Custom>;
}
