import { EditorialPage } from "@/components/EditorialPage";

export default function TermsPage() { return <EditorialPage eyebrow="TERMS & CONDITIONS · EFFECTIVE 15 AUGUST 2026" title={<>Collection<br/><em>terms.</em></>} intro="These terms govern access to One Minute of You and participation in its 500-work generative NFT collection.">
  <section><h2>1. The experience</h2><p>One Minute of You converts locally captured pointer, touch, or stylus movement into deterministic generative artwork. The visual result, Royal House, traits, and SHA-256 seed are derived by the published renderer version.</p></section>
  <section><h2>2. Eligibility and wallets</h2><p>You must be legally able to enter binding transactions where you live. You control your wallet, private keys, device, network selection, and transaction approvals. The House of Joshi cannot recover keys or reverse blockchain transactions.</p></section>
  <section><h2>3. Minting and royalties</h2><p>Supply is limited to 500 tokens, subject to smart-contract availability. Primary mint proceeds are withdrawable only to the published House treasury. The contract signals a 7% secondary-sale royalty through ERC-2981, but marketplace support and payment are not guaranteed. Before confirmation, review the artwork, network, contract address, mint price, gas estimate, metadata URI, and connected wallet.</p></section>
  <section><h2>4. Ownership and use</h2><p>Owning a token means owning that blockchain token. Unless a separate written licence states otherwise, project names, trademarks, interface, renderer code, and brand assets remain the property of The House of Joshi. Token ownership does not grant ownership of the platform or its trademarks.</p></section>
  <section><h2>5. Marketplaces and third parties</h2><p>OpenSea, Base, wallet providers, IPFS gateways, exchanges, and other linked services operate independently. Their availability, indexing, fees, listings, offers, and policies are outside our control.</p></section>
  <section><h2>6. Risks and no financial promise</h2><p>NFTs and crypto-assets can lose all market value. Nothing in the app is financial, investment, legal, or tax advice. No appreciation, liquidity, utility, resale opportunity, or future feature is promised.</p></section>
  <section><h2>7. Acceptable use</h2><p>Do not interfere with the service, bypass mint limits, exploit vulnerabilities, automate abusive requests, misrepresent provenance, or use the project unlawfully.</p></section>
  <section><h2>8. Availability and changes</h2><p>We may maintain, pause, update, or discontinue hosted interfaces. On-chain records and permanently pinned assets remain governed by their respective networks and storage systems.</p></section>
  <section><h2>9. Disclaimer and liability</h2><p>The service is provided as available, without guarantees of uninterrupted operation. To the maximum extent permitted by law, The House of Joshi is not liable for wallet compromise, user error, network failure, marketplace action, lost keys, or indirect losses.</p></section>
  <section><h2>10. Contact</h2><p>Questions about these terms can be submitted through <a href="https://thehouseofjoshi.com/contact" target="_blank" rel="noreferrer">The House of Joshi contact page ↗</a>.</p></section>
 </EditorialPage>; }
